version: "3.9"

services:
  flask:
    build:
      context: .
      target: production
    image: flask-app:multistage
    container_name: flask-hardened
    ports:
      - "127.0.0.1:5000:5000"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - FLASK_DEBUG=false
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=dev-root-token
    restart: unless-stopped
    depends_on:
      vault:
        condition: service_started
    networks:
      - appnet

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: server -dev
    networks:
      - appnet

networks:
  appnet:
    driver: bridge