apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: flask-app
type: Opaque
stringData:
  db_password: "SecureDbPassword123"
  secret_key: "flask-secret-key-change-in-prod"